apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civicproof-ingress
  namespace: civicproof
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - api.civicproof.gov.in
        - app.civicproof.gov.in
      secretName: civicproof-tls-cert
  rules:
    - host: api.civicproof.gov.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: civicproof-api-service
                port:
                  number: 80
